service:
  name: what-im-reading-backend

plugins:
  - serverless-offline
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 512

functions:
  prismic:
    handler: prismic.webhook
    events:
      - http:
          method: GET
          path: prismic
      - http:
          method: POST
          path: prismic
  kentico:
    handler: kentico.webhook
    timeout: 5
    events:
      - http:
          method: GET
          path: kentico
      - http:
          method: POST
          path: kentico


custom:
  customDomain:
    domainName: lambda.fox.engineer
    basePath: 'reading'
    stage: ${self:provider.stage}
    createRoute53Record: true
